# Generated by Django 5.2 on 2025-05-05 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_bag_article_alter_bag_bag_type_alter_bag_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagimage',
            options={'verbose_name': 'Изображение сумки', 'verbose_name_plural': 'Изображения сумок'},
        ),
        migrations.AlterModelOptions(
            name='bagtype',
            options={'verbose_name': 'Тип'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд'},
        ),
        migrations.AlterField(
            model_name='bagimage',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.bag'),
        ),
        migrations.AlterField(
            model_name='bagimage',
            name='image',
            field=models.ImageField(upload_to='bags/'),
        ),
    ]
