# Generated by Django 5.2 on 2025-05-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bagtype_brand_color_material_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bags/extra/')),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='shop.bag')),
            ],
        ),
    ]
