# Generated by Django 5.2 on 2025-05-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bagimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='bags/'),
        ),
    ]
