# Generated by Django 5.2 on 2025-05-05 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bag_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bag_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.bagtype'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='characteristics',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bag',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.material'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size'),
        ),
    ]
