# Generated by Django 5.2 on 2025-05-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_bagimage_options_alter_bagtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Брэнд', 'verbose_name_plural': 'Брэнды'},
        ),
    ]
