# Generated by Django 5.2 on 2025-05-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_bagtype_options_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': 'Сумка', 'verbose_name_plural': 'Сумки'},
        ),
    ]
