# Generated by Django 5.2 on 2025-05-05 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_color_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
