# Generated by Django 5.2 on 2025-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='article',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Артикул'),
        ),
    ]
