# Generated by Django 5.2 on 2025-05-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_bag_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={'verbose_name': 'Сумку', 'verbose_name_plural': 'Сумки'},
        ),
    ]
