# Generated by Django 5.2 on 2025-05-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_bag_color_bag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='color',
        ),
        migrations.AddField(
            model_name='bag',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Цвет'),
        ),
    ]
